### ISSUE TITLE
Android Studio - Not a Gradle based Project

### ISSUE THREAD

**Issue by n00823698** [sozialhelden/wheelmap-android#65]
Having issues importing into Android Studio. Says not a gradle based project also the following error:

Error:Android Source Generator: [wheelmap-android] AndroidManifest.xml file not found

**Comment by michalharakal** [comment]
The message is correct. Project has not been ported to gradle yet. It uses maven as underlaying build system. See [README file!](https://github.com/sozialhelden/wheelmap-android/blob/master/wheelmap/README) how to build it.
